apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: observability
resources:
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
  - sa-and-ra.yaml
  - prometheus.yaml
  - service.yaml
  - secret.yaml
  - ingress.yaml
  - monitor.yaml