apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: ClientIP
  ports:
  - name: web
    port: 9090
    targetPort: web
