apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-ingress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
      name: https

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-observability
spec:
  type: ClusterIP
  selector:
    app: nginx-ingress
  ports:
    - port: 9090
      targetPort: 9113
      protocol: TCP
      name: prometheus