apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simple-replicaset
spec:
  containers:
  - name: simple-pod
    image: rutush10/simple-restapi-server-py:v0.0.1
    ports:
    - containerPort: 8000
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi